import React from 'react';
import { useAppStore } from '../stores/appStore';
import { apiClient } from '../lib/api/client';
import { Search, Users, UserRound, Smartphone, Bell, Eye, Ban, CircleHelp, Server, WifiOff, AlertTriangle, CheckCircle2, Image as ImageIcon, MessageCircle, Flag } from 'lucide-react';

type Item = { title:string; subtitle?:string; icon?:React.ElementType; route?:string };

const ShellPage: React.FC<{title:string;subtitle:string;children?:React.ReactNode;action?:React.ReactNode}> = ({title,subtitle,children,action}) => <section className="space-y-5"><div className="flex flex-wrap items-end justify-between gap-3"><div><h1 className="text-2xl sm:text-3xl font-black tracking-tight">{title}</h1><p className="text-sm text-stone-500 mt-1">{subtitle}</p></div>{action}</div>{children}</section>;
const Card: React.FC<{children:React.ReactNode;className?:string}> = ({children,className=''}) => <div className={`rounded-2xl border border-stone-200 dark:border-stone-800 bg-white dark:bg-stone-900 shadow-sm ${className}`}>{children}</div>;

const Rows: React.FC<{items:Item[]}> = ({items}) => { const {navigate}=useAppStore(); return <Card className="divide-y divide-stone-100 dark:divide-stone-800 overflow-hidden">{items.map((x,i)=>{const I=x.icon||CircleHelp; const content=<><span className="w-10 h-10 rounded-xl bg-emerald-50 dark:bg-emerald-950/50 text-emerald-700 dark:text-emerald-300 flex items-center justify-center"><I size={19}/></span><span className="flex-1"><span className="block font-semibold text-sm">{x.title}</span>{x.subtitle&&<span className="block text-xs text-stone-500 mt-0.5">{x.subtitle}</span>}</span>{x.route&&<span className="text-stone-400">›</span>}</>; return x.route?<button key={i} onClick={()=>navigate(x.route!)} className="w-full flex items-center gap-4 p-4 text-left hover:bg-stone-50 dark:hover:bg-stone-800/60 transition">{content}</button>:<div key={i} className="w-full flex items-center gap-4 p-4">{content}</div>})}</Card>; };

export const ExploreView:React.FC=()=>{const {navigate}=useAppStore();return <ShellPage title="Explore" subtitle="Discover server-backed communities and content."><Card className="p-4 flex items-center gap-3"><Search size={19}/><input onFocus={()=>navigate('/search')} className="flex-1 bg-transparent outline-none text-sm" placeholder="Search Everything IOP"/></Card><button onClick={()=>navigate('/communities')} className="ev-primary">Browse Communities</button></ShellPage>};

export const CreatePostView:React.FC=()=>{const {createPost,navigate}=useAppStore();const [text,setText]=React.useState('');const [busy,setBusy]=React.useState(false);const [error,setError]=React.useState('');return <ShellPage title="Create post" subtitle="Publish through the authenticated Everything IOP API." action={<button onClick={()=>navigate('/home')}>Cancel</button>}><Card className="p-5 space-y-4"><textarea value={text} onChange={e=>setText(e.target.value)} className="w-full min-h-48 resize-none bg-transparent outline-none" placeholder="What's happening?"/><div className="flex justify-end"><button disabled={!text.trim()||busy} onClick={async()=>{setBusy(true);setError('');const ok=await createPost(text.trim(),'public');setBusy(false);if(ok)navigate('/home');else setError('The server rejected the post. Nothing was marked as published.')}} className="ev-primary disabled:opacity-50">{busy?'Publishing…':'Publish'}</button></div>{error&&<p className="text-sm text-rose-600">{error}</p>}</Card></ShellPage>};

export const FollowersView:React.FC<{mode:'followers'|'following'}>=({mode})=><ShellPage title={mode==='followers'?'Followers':'Following'} subtitle="Connections returned by the server."><ServerList endpoint={mode==='followers'?'/users/me/followers':'/users/me/following'} empty="No connections returned by the server."/></ShellPage>;

export const SettingsSectionView:React.FC<{section:string}>=({section})=>{const {navigate,toggleDarkMode,isDarkMode}=useAppStore();const labels:Record<string,string>={account:'Account',privacy:'Privacy',notifications:'Notifications',appearance:'Appearance'};return <ShellPage title={labels[section]||'Settings'} subtitle="Server-backed account preferences." action={<button onClick={()=>navigate('/settings')}>All settings</button>}><Rows items={[{title:'Profile information',subtitle:'Name, username and bio',icon:UserRound,route:'/profile'},{title:'Security center',subtitle:'Password, sessions and security controls',icon:Smartphone,route:'/settings/security'},{title:'Notifications',subtitle:'Notification preferences',icon:Bell,route:'/settings/notifications'},{title:'Blocked users',subtitle:'Server-backed blocked accounts',icon:Ban,route:'/settings/blocked'}]}/>{section==='appearance'&&<Card className="p-4"><button onClick={toggleDarkMode} className="w-full py-3 rounded-xl bg-emerald-800 text-white">{isDarkMode?'Switch to light mode':'Switch to dark mode'}</button></Card>}</ShellPage>};

export const SessionsView:React.FC=()=> <ShellPage title="Sessions & devices" subtitle="Active sessions from the authenticated server."><ServerList endpoint="/auth/sessions" empty="No other active sessions returned."/></ShellPage>;
export const BlockedUsersView:React.FC=()=> <ShellPage title="Blocked users" subtitle="Blocked accounts are controlled by the server."><ServerList endpoint="/safety/blocked" empty="No blocked users returned."/></ShellPage>;
export const ReportView:React.FC=()=> <ShellPage title="Reports" subtitle="Your safety reports and decisions from the server."><ServerList endpoint="/safety/reports" empty="No reports returned."/></ShellPage>;
export const HelpCenterView:React.FC=()=> <ShellPage title="Help & support" subtitle="Server-backed support resources."><Rows items={[{title:'Getting started',icon:CircleHelp,route:'/help'},{title:'Safety & reporting',icon:Flag,route:'/reports'},{title:'Contact support',icon:MessageCircle,route:'/support'}]}/></ShellPage>;

export const ForgotPasswordView:React.FC=()=>{const [identifier,setIdentifier]=React.useState('');const [busy,setBusy]=React.useState(false);const {addToast,navigate}=useAppStore();return <ShellPage title="Forgot password" subtitle="Start the server-backed password reset flow."><Card className="p-5 space-y-4"><input value={identifier} onChange={e=>setIdentifier(e.target.value)} className="w-full rounded-xl border p-3 bg-transparent" placeholder="Email or username"/><button disabled={!identifier.trim()||busy} onClick={async()=>{setBusy(true);try{await apiClient.request('/auth/password-reset',{method:'POST',body:JSON.stringify({identifier:identifier.trim()})});addToast('Reset request accepted by the server.','success');navigate('/login')}catch(e:any){addToast(e.message||'Reset request failed.','error')}finally{setBusy(false)}}} className="w-full ev-primary disabled:opacity-50">{busy?'Sending…':'Send reset link'}</button></Card></ShellPage>};

export const ResetPasswordView:React.FC=()=>{const [password,setPassword]=React.useState('');const [confirm,setConfirm]=React.useState('');const {addToast,navigate}=useAppStore();return <ShellPage title="Reset password" subtitle="Complete the server-backed reset flow."><Card className="p-5 space-y-3"><input value={password} onChange={e=>setPassword(e.target.value)} type="password" className="w-full rounded-xl border p-3 bg-transparent" placeholder="New password"/><input value={confirm} onChange={e=>setConfirm(e.target.value)} type="password" className="w-full rounded-xl border p-3 bg-transparent" placeholder="Confirm password"/><button disabled={!password||password!==confirm} onClick={async()=>{try{await apiClient.request('/auth/password-reset/confirm',{method:'POST',body:JSON.stringify({password})});addToast('Password updated by the server.','success');navigate('/login')}catch(e:any){addToast(e.message||'Password update failed.','error')}}} className="w-full ev-primary disabled:opacity-50">Update password</button></Card></ShellPage>};

export const CommunityMembersView:React.FC=()=> <ShellPage title="Community members" subtitle="Members are loaded from the selected community server resource."><ServerList endpoint="/communities/current/members" empty="No members returned by the server."/></ShellPage>;
export const CommunityRulesView:React.FC=()=> <ShellPage title="Community rules" subtitle="Rules returned by the community server resource."><ServerList endpoint="/communities/current/rules" empty="No rules returned by the server."/></ShellPage>;
export const ChatInfoView:React.FC=()=> <ShellPage title="Chat information" subtitle="Conversation metadata and controls are server-backed."><Rows items={[{title:'Media, links and files',icon:ImageIcon},{title:'Mute notifications',icon:Bell},{title:'Block participant',icon:Ban},{title:'Report conversation',icon:Flag}]}/></ShellPage>;

export const CreateStoryView:React.FC=()=>{const [text,setText]=React.useState('');const {addToast,navigate}=useAppStore();return <ShellPage title="Create story" subtitle="Publish a story through the authenticated server."><Card className="p-5 space-y-4"><textarea value={text} onChange={e=>setText(e.target.value)} className="w-full min-h-36 rounded-xl border p-4 bg-transparent" placeholder="Write your story…"/><button disabled={!text.trim()} onClick={async()=>{try{await apiClient.request('/stories',{method:'POST',body:JSON.stringify({text:text.trim()})});addToast('Story published by the server.','success');navigate('/home')}catch(e:any){addToast(e.message||'Story publish failed.','error')}}} className="w-full ev-primary disabled:opacity-50">Publish</button></Card></ShellPage>};

export const SupportView:React.FC=()=>{const [subject,setSubject]=React.useState('');const [body,setBody]=React.useState('');const {addToast}=useAppStore();return <ShellPage title="Contact support" subtitle="Create a real support request on the server."><Card className="p-5 space-y-4"><input value={subject} onChange={e=>setSubject(e.target.value)} className="w-full rounded-xl border p-3 bg-transparent" placeholder="Subject"/><textarea value={body} onChange={e=>setBody(e.target.value)} className="w-full min-h-40 rounded-xl border p-3 bg-transparent" placeholder="Describe the issue"/><button disabled={!subject.trim()||!body.trim()} onClick={async()=>{try{await apiClient.request('/safety/support',{method:'POST',body:JSON.stringify({subject:subject.trim(),body:body.trim()})});addToast('Support request submitted to the server.','success');setSubject('');setBody('')}catch(e:any){addToast(e.message||'Support request failed.','error')}}} className="w-full ev-primary disabled:opacity-50">Submit</button></Card></ShellPage>};

export const ServerStatusView:React.FC=()=>{const [status,setStatus]=React.useState('checking');React.useEffect(()=>{apiClient.checkHealth().then(r=>setStatus(r.status)).catch(()=>setStatus('unavailable'))},[]);return <ShellPage title="Server status" subtitle="Live Node.js health check."><Card className="p-6 flex gap-4 items-center"><Server/><div><b>{status==='ok'?'Everything IOP server online':status==='checking'?'Checking server…':'Everything IOP server unavailable'}</b><p className="text-sm text-stone-500">Status is read from the backend health endpoint.</p></div></Card></ShellPage>};

export const SystemStateView:React.FC<{kind:'offline'|'error'|'404'}>=({kind})=>{const {navigate}=useAppStore();const cfg=kind==='offline'?{icon:WifiOff,title:'You are offline',text:'The server connection is unavailable.'}:kind==='error'?{icon:AlertTriangle,title:'Something went wrong',text:'The server returned an unexpected error.'}:{icon:Search,title:'Page not found',text:'The requested route does not exist.'};const I=cfg.icon;return <div className="min-h-[60vh] flex items-center justify-center"><Card className="max-w-md p-8 text-center"><I className="mx-auto text-emerald-700" size={40}/><h1 className="text-2xl font-black mt-4">{cfg.title}</h1><p className="text-sm text-stone-500 mt-2">{cfg.text}</p><button onClick={()=>navigate('/home')} className="mt-6 px-5 py-2.5 rounded-xl bg-emerald-800 text-white">Back to Home</button></Card></div>};

function ServerList({endpoint,empty}:{endpoint:string;empty:string}){const [state,setState]=React.useState<'loading'|'ready'|'error'>('loading');const [items,setItems]=React.useState<any[]>([]);React.useEffect(()=>{apiClient.request<any[]>(endpoint).then(r=>{setItems(r.data||[]);setState('ready')}).catch(()=>setState('error'))},[endpoint]);if(state==='loading')return <Card className="p-6">Loading server data…</Card>;if(state==='error')return <Card className="p-6 text-rose-600">The server did not return this resource.</Card>;if(items.length===0)return <Card className="p-6 text-stone-500">{empty}</Card>;return <Card className="divide-y divide-stone-100 dark:divide-stone-800">{items.slice(0,100).map((x:any,i)=><div className="p-4 flex gap-3" key={String(x.id||i)}><CheckCircle2 size={18}/><div><b>{String(x.name||x.username||x.device||x.title||x.id||`Record ${i+1}`)}</b><p className="text-xs text-stone-500">Server record</p></div></div>)}</Card>}
