import React, { useState } from 'react';
import CoinMessageComposer from './CoinMessageComposer';
import { apiClient } from '../../lib/api/client';
import { CalendarDays, Check, ChevronRight, KeyRound, Copy, Download, FileText, Flag, Heart, Image, Link2, Lock, Mail, MessageCircle , Play, Plus, Save, Search, Send, Settings, ShieldCheck, ShoppingBag, Smartphone, Trash2, Upload, UserPlus, Video, Wallet, Webhook, X, Zap } from 'lucide-react';

type Props = { id: string; title: string; notify: (message: string) => void; go?: (id: string) => void; surfaceId?: string };

const Button = ({children, onClick, primary=false, disabled=false, type='button'}: any) => <button type={type} disabled={disabled} aria-disabled={disabled} className={primary ? 'ev-primary' : 'ev-outline'} onClick={onClick}>{children}</button>;
const Field = ({label, children}: any) => <label className="ev-workflow-field"><span>{label}</span>{children}</label>;
const CheckRow = ({children}: any) => <div className="ev-check-row"><Check size={14}/><span>{children}</span></div>;

async function serverAction(endpoint: string, method: 'POST'|'PATCH'|'DELETE' = 'POST', body?: unknown) {
  const response = await apiClient.request(endpoint, { method, body: body === undefined ? undefined : JSON.stringify(body) });
  if (!response.success) throw new Error('Server rejected the operation.');
  return response;
}

function ContentWorkflow({id, notify, go, surfaceId}: Props){
  const [editorText, setEditorText] = useState('');
  const [saving, setSaving] = useState(false);
  const applyFormat = (prefix: string, suffix = prefix) => setEditorText((v) => `${prefix}${v || 'text'}${suffix}`);
  const insertToken = (token: string) => setEditorText((v) => `${v}${v ? '\n' : ''}${token}`);
  const publish = () => {
    if (!editorText.trim()) { notify(id === 'html' ? 'Add HTML content before publishing.' : 'Write something before publishing.'); return; }
    setSaving(true);
    serverAction(id === 'html' ? '/html/posts' : '/posts', 'POST', { content: editorText, contentType: id === 'html' ? 'html' : 'text' }).then(() => notify(id === 'html' ? 'HTML post published.' : 'Post published.')).catch((e) => notify(e.message || 'Publish failed.')).finally(() => setSaving(false));
  };
  if(id==='post' || id==='html') return <><div className="ev-workflow-editor"><div className="ev-editor-toolbar"><button type="button" aria-label="Bold" onClick={()=>applyFormat('**') }><b>B</b></button><button type="button" aria-label="Italic" onClick={()=>applyFormat('_') }><i>I</i></button><button type="button" aria-label="Insert link" onClick={()=>insertToken('[link](https://example.com)')}><Link2 size={15}/></button><button type="button" aria-label="Insert image" onClick={()=>insertToken('![image](https://example.com/image.jpg)')}><Image size={15}/></button></div><textarea value={editorText} onChange={e=>setEditorText(e.target.value)} aria-label={id==='html' ? 'Safe HTML content' : 'Post content'} aria-invalid={!editorText.trim()} placeholder={id==='html' ? '<p>Write safe HTML here...</p>' : 'What do you want to share?'}/><div className="ev-editor-preview"><span className="ev-eyebrow">LIVE PREVIEW</span><p>{id==='html' ? 'Sanitized HTML preview appears here. Scripts, event handlers and unsafe embeds are rejected.' : 'Your post preview will appear here.'}</p></div></div><div className="ev-workflow-actions"><Button onClick={()=>{ if (!editorText.trim()) { notify('Nothing to save yet.'); return; } serverAction('/posts/drafts', 'POST', { content: editorText, contentType: id }).then(() => notify('Draft saved on the server.')).catch((e) => notify(e.message || 'Draft save failed.')); }}><Save size={15}/> Save draft</Button><Button primary onClick={publish} disabled={saving}>{saving ? 'Publishing…' : <><Check size={15}/> Publish</>}</Button></div></>;
  if(id==='reel') return <><div className="ev-upload-stage"><Play size={38}/><b>Reel preview</b><span>Vertical 9:16 · music · captions · products</span><label className="ev-outline" style={{display:'inline-flex',alignItems:'center',gap:6,cursor:'pointer'}}><Upload size={15}/> Add video<input type="file" accept="video/mp4,video/webm" hidden /></label></div><div className="ev-form-grid"><Field label="Caption"><input placeholder="Describe your Reel"/></Field><Field label="Audio"><select><option>Original audio</option><option>Trending audio</option><option>Upload audio</option></select></Field><Field label="Audience"><select><option>Everyone</option><option>Followers</option><option>Subscribers</option></select></Field><Field label="Comments"><select><option>Allow</option><option>Followers only</option><option>Off</option></select></Field></div><Button primary onClick={()=>serverAction('/reels', 'POST', { status: 'draft' }).then(() => notify('Reel draft created on the server.')).catch((e) => notify(e.message || 'Reel creation failed.'))}><Check size={15}/> Continue</Button>{surfaceId ? <CoinMessageComposer surfaceId={surfaceId} surfaceType="reel" /> : <div className="ev-integration-required">Coin messages require a real Reel ID.</div>}</>;
  if(id==='video' || id==='channel') return <><div className="ev-upload-stage"><Video size={38}/><b>{id==='video'?'Video upload':'Channel manager'}</b><span>{id==='video'?'Upload video, thumbnail, captions and chapters':'Manage channel identity, playlists, memberships and posts'}</span><label className="ev-outline" style={{display:'inline-flex',alignItems:'center',gap:6,cursor:'pointer'}}><Upload size={15}/> Select file<input type="file" accept="video/mp4,video/webm" hidden /></label></div><div className="ev-form-grid"><Field label="Title"><input placeholder="Video title"/></Field><Field label="Visibility"><select><option>Public</option><option>Unlisted</option><option>Private</option></select></Field><Field label="Category"><select><option>Education</option><option>Entertainment</option><option>Gaming</option><option>Business</option></select></Field><Field label="Playlist"><select><option>Watch later</option><option>Creator series</option><option>Create playlist</option></select></Field></div><div className="ev-check-list"><CheckRow>Captions can be added after upload</CheckRow><CheckRow>Products and communities can be attached</CheckRow><CheckRow>Monetization eligibility is checked by backend later</CheckRow></div><Button primary onClick={()=>serverAction(id === 'video' ? '/videos' : '/channels', 'POST', { status: 'draft' }).then(() => notify('Changes saved on the server.')).catch((e) => notify(e.message || 'Save failed.'))}><Save size={15}/> Save</Button>{id==='video' && (surfaceId ? <CoinMessageComposer surfaceId={surfaceId} surfaceType="video" /> : <div className="ev-integration-required">Coin messages require a real Video ID.</div>)}</>;
  if(id==='live' || id==='live-studio') return <><div className="ev-live-setup"><div className="ev-live-preview"><Video size={38}/><span>Camera / encoder preview</span></div><div className="ev-live-settings"><Field label="Title"><input placeholder="Live session title"/></Field><Field label="Audience"><select><option>Everyone</option><option>Followers</option><option>Subscribers</option><option>Community members</option></select></Field><Field label="Chat"><select><option>On · moderated</option><option>Subscribers only</option><option>Off</option></select></Field><Field label="Products"><select><option>No products</option><option>Attach creator products</option></select></Field></div></div><div className="ev-workflow-actions"><Button onClick={()=>serverAction('/live', 'POST', { status: 'configured' }).then(() => notify('Stream settings saved on the server.')).catch((e) => notify(e.message || 'Save failed.'))}><Save size={15}/> Save setup</Button><Button primary onClick={()=>serverAction('/live/preview', 'POST').then(() => notify('Live preview started by the server.')).catch((e) => notify(e.message || 'Live preview failed.'))}><Play size={15}/> Start preview</Button></div>{surfaceId ? <CoinMessageComposer surfaceId={surfaceId} surfaceType="live" /> : <div className="ev-integration-required">Coin messages require a real Live ID.</div>}</>;
  if(id==='media') return <div className="ev-media-workflow"><div className="ev-media-canvas"><Image size={52}/><span>Fullscreen media viewer</span><small>Swipe · zoom · rotate · save · share</small></div><div className="ev-media-tools"><Button onClick={()=>serverAction('/media/actions', 'POST', { action: 'save' }).then(() => notify('Media saved.')).catch((e) => notify(e.message || 'Save failed.'))}><Save size={15}/> Save</Button><Button onClick={()=>navigator.share ? navigator.share({ title: 'Everything IOP media', url: window.location.href }).catch(() => undefined) : navigator.clipboard?.writeText(window.location.href).then(() => notify('Link copied.'))}><Send size={15}/> Share</Button><Button onClick={()=>serverAction('/media/actions', 'POST', { action: 'download', url: window.location.href }).then(() => notify('Download authorized by the server.')).catch((e) => notify(e.message || 'Download unavailable.'))}><Download size={15}/> Download</Button><Button onClick={()=>go?.('report')}><Flag size={15}/> Report</Button></div></div>;
  return <GenericWorkflow title={titleFor(id)} notify={notify} go={go}/>;
}

function CommerceWorkflow({id, notify, go}: Props){
  const [productName, setProductName] = useState('');
  const [price, setPrice] = useState('');
  const [stock, setStock] = useState('');
  if(id==='event') return <><div className="ev-form-grid"><Field label="Event title"><input placeholder="Event title"/></Field><Field label="Audience"><select><option>Public</option><option>Followers</option><option>Subscribers</option><option>Community members</option></select></Field><Field label="Ticketing"><select><option>Free</option><option>Paid</option></select></Field></div><div className="ev-check-list"><CheckRow>Reminders and deep links are supported</CheckRow><CheckRow>Live chat, reactions and sharing can be attached</CheckRow><CheckRow>Payment status must be confirmed by the backend</CheckRow></div><Button primary onClick={()=>serverAction('/events', 'POST', { status: 'draft' }).then(() => notify('Event draft created on the server.')).catch((e) => notify(e.message || 'Event creation failed.'))}><CalendarDays size={15}/> Continue</Button></>;
  const saveListing = () => {
    const amount = Number(price);
    const units = Number(stock);
    if (!productName.trim()) return notify('Product name is required.');
    if (!Number.isFinite(amount) || amount <= 0) return notify('Enter a valid price greater than 0.');
    if (!Number.isInteger(units) || units < 0) return notify('Enter valid stock (0 or more).');
    serverAction('/products', 'POST', { name: productName, price: amount, stock: units }).then(() => notify('Listing saved on the server.')).catch((e) => notify(e.message || 'Listing save failed.'));
  };
  if(id==='seller') return <><div className="ev-seller-grid"><div className="ev-balance-grid"><div><span>Products</span><b>128</b></div><div><span>Pending orders</span><b>12</b></div><div><span>Revenue</span><b>$48.2K</b></div></div><div className="ev-form-grid"><Field label="Catalog visibility"><select><option>Public</option><option>Followers</option><option>Private</option></select></Field><Field label="Default fulfillment"><select><option>Buyer / seller direct</option><option>Connected logistics</option></select></Field></div></div><div className="ev-table-wrap"><table className="ev-table"><thead><tr><th>Area</th><th>Status</th><th>Action</th></tr></thead><tbody>{[['Catalog','Healthy','Manage'],['Orders','12 pending','Open'],['Payouts','Verified','View'],['Returns','1 open','Review']].map((r)=><tr key={r[0]}><td><b>{r[0]}</b></td><td>{r[1]}</td><td><button className="ev-link-btn" onClick={()=>notify(`${r[0]} opened`)}>{r[2]}</button></td></tr>)}</tbody></table></div><Button primary onClick={()=>serverAction('/seller/settings', 'PATCH', { updated: true }).then(() => notify('Seller settings saved on the server.')).catch((e) => notify(e.message || 'Seller settings failed.'))}><Save size={15}/> Save seller settings</Button></>;
  if(id==='product' || id==='seller-product') return <><div className="ev-product-builder"><div className="ev-product-image"><ShoppingBag size={40}/><label className="ev-outline" style={{display:'inline-flex',alignItems:'center',gap:6,cursor:'pointer'}}><Upload size={15}/> Add media<input type="file" accept="image/png,image/jpeg,image/webp" multiple hidden /></label></div><div className="ev-form-grid"><Field label="Product name"><input value={productName} onChange={e=>setProductName(e.target.value)} required aria-required="true" placeholder="Product name"/></Field><Field label="Price"><input value={price} onChange={e=>setPrice(e.target.value)} required aria-required="true" min="0.01" step="0.01" type="number" placeholder="0.00"/></Field><Field label="Stock"><input value={stock} onChange={e=>setStock(e.target.value)} required aria-required="true" min="0" step="1" type="number" placeholder="0"/></Field><Field label="Condition"><select><option>New</option><option>Used</option><option>Digital</option></select></Field></div></div><Field label="Description"><textarea placeholder="Describe the product, delivery expectations and terms"/></Field><div className="ev-check-list"><CheckRow>Product can be attached to posts, Reels, videos and communities</CheckRow><CheckRow>Buyer/seller delivery responsibility is clearly shown</CheckRow><CheckRow>Payment/refund state comes from backend later</CheckRow></div><Button primary onClick={saveListing}><Save size={15}/> Save listing</Button></>;
  if(id==='buyer-chat') return <><div className="ev-commerce-context"><ShoppingBag size={20}/><div><b>Creator Desk Kit</b><span>$89 · North Studio · Product context stays attached to chat</span></div></div><div className="ev-chat-preview">{['Hi, is this still available?','Yes — 42 in stock.','Can you confirm delivery details?'].map((x,i)=><div className={i%2?'mine':''} key={x}>{x}</div>)}</div><div className="ev-chat-compose"><input placeholder="Message seller..."/><button onClick={()=>serverAction('/conversations', 'POST', { type: 'seller-inquiry' }).then(() => notify('Seller conversation created on the server.')).catch((e) => notify(e.message || 'Unable to contact seller.'))}><Send size={16}/></button><button onClick={()=>go?.('buyer-chat')}><Plus size={16}/></button></div></>;
  if(id==='order') return <><div className="ev-timeline">{['Inquiry created','Seller replied','Payment reference received','Delivery arranged','Completed / issue'].map((x,i)=><div key={x} className={i<3?'done':''}><span>{i+1}</span><div><b>{x}</b><small>{i<3?'Completed':'Available when applicable'}</small></div></div>)}</div><div className="ev-workflow-actions"><Button onClick={()=>go?.('buyer-chat')}><MessageCircle size={15}/> Message seller</Button><Button onClick={()=>go?.('report')}><Flag size={15}/> Report issue</Button></div></>;
  if(id==='ads') return <><div className="ev-form-grid"><Field label="Campaign name"><input placeholder="Campaign name"/></Field><Field label="Objective"><select><option>Sales</option><option>Reach</option><option>Engagement</option></select></Field><Field label="Placement"><select><option>Automatic</option><option>Feed</option><option>Reels</option><option>Videos</option><option>Communities</option><option>Search</option></select></Field><Field label="Budget"><input type="number" placeholder="Daily budget"/></Field></div><div className="ev-sponsor-note"><ShieldCheck size={17}/><span>Sponsored / Advertisement labels are shown on eligible placements.</span></div><Button primary onClick={()=>notify('Campaign draft saved')}><Save size={15}/> Save campaign</Button></>;
  return <GenericWorkflow title={titleFor(id)} notify={notify} go={go}/>;
}

function CommunityWorkflow({id, notify, go}: Props){
  if(id==='members') return <><div className="ev-inline-search"><Search size={16}/><input placeholder="Search members"/></div><div className="ev-member-list">{['Ayaan Studio','Mina Crafts','Rayan Nova','Night Vision','Pixel Lab'].map((x,i)=><div key={x}><div className="ev-avatar tiny">{x.slice(0,2)}</div><div><b>{x}</b><span>@{x.toLowerCase().replaceAll(' ','')} · {i===0?'Owner':'Member'}</span></div><select defaultValue={i===0?'Owner':'Member'}><option>Owner</option><option>Admin</option><option>Moderator</option><option>Verified</option><option>VIP</option><option>Member</option><option>Guest</option></select><button onClick={()=>notify(`${x} role updated`)}><Check size={15}/></button></div>)}</div></>;
  if(id==='channels') return <><div className="ev-channel-builder">{['General','Announcements','Forum','Media','Q&A','Voice','Video','Events'].map((x,i)=><button key={x} onClick={()=>notify(`${x} channel opened`)}><MessageCircle size={17}/><b>{x}</b><span>{i%2?'Read-only announcements':'Scoped permissions'}</span><ChevronRight size={15}/></button>)}</div><Button primary onClick={()=>notify('Channel creation form is ready')}><Plus size={15}/> Create channel</Button></>;
  if(id==='moderation') return <><div className="ev-filter-row"><button className="active" onClick={()=>notify('Moderation filter: Open')}>Open 12</button><button onClick={()=>notify('Moderation filter: Assigned')}>Assigned 4</button><button onClick={()=>notify('Moderation filter: Resolved')}>Resolved 38</button></div><div className="ev-moderation-list">{['Spam report · post #1842','Harassment report · comment #92','Suspicious link · message #441','Member appeal · @rayanova'].map(x=><div key={x}><Flag size={17}/><div><b>{x}</b><span>Needs review · evidence attached</span></div><Button onClick={()=>notify('Moderation item selected')}>Review</Button></div>)}</div></>;
  if(id==='automation') return <><div className="ev-automation-flow"><div><span>WHEN</span><b>member joins</b></div><ChevronRight/><div><span>IF</span><b>verified</b></div><ChevronRight/><div><span>THEN</span><b>welcome + assign role</b></div></div><div className="ev-form-grid"><Field label="Trigger"><select><option>Member joins</option><option>Post created</option><option>Report created</option><option>Event starts</option></select></Field><Field label="Condition"><select><option>Verified member</option><option>New account</option><option>Has role</option></select></Field><Field label="Action"><select><option>Send message</option><option>Assign role</option><option>Create ticket</option><option>Notify moderators</option></select></Field></div><Button primary onClick={()=>notify('Automation saved')}><Zap size={15}/> Save automation</Button></>;
  if(id==='community-store') return <><div className="ev-product-grid">{['Community Badge Pack','Workshop Ticket','Member Bundle'].map((x,i)=><div className="ev-card" key={x}><div className="ev-product-image"><ShoppingBag size={28}/></div><h3>{x}</h3><p>Community-only commerce surface · {i+1} tier</p><Button onClick={()=>go?.(({ 'Notification categories':'notifications', 'Theme & density':'appearance', 'Language & region':'language', 'Messaging controls':'messages-settings', 'Content preferences':'content-controls', 'Help & support':'help' } as Record<string,string>)[x] || 'help')}>Manage product</Button></div>)}</div><Button primary onClick={()=>go?.('seller-product')}><Plus size={15}/> Add community product</Button></>;
  if(id==='community-analytics') return <><div className="ev-metrics four"><div className="ev-metric"><span>Members</span><strong>48.2K</strong></div><div className="ev-metric"><span>Engagement</span><strong>9.7%</strong></div><div className="ev-metric"><span>Revenue</span><strong>$8.2K</strong></div><div className="ev-metric"><span>Events</span><strong>24</strong></div></div><div className="ev-check-list"><CheckRow>Analytics are scoped to the community owner and permitted staff.</CheckRow><CheckRow>Revenue excludes pending refunds, chargebacks and provider fees.</CheckRow></div></>;
  if(id==='bots') return <><div className="ev-app-list">{['Welcome Bot','Analytics Bot','Moderation App','Events Assistant'].map((x,i)=><div key={x}><div className="ev-tile-icon">⚙</div><div><b>{x}</b><span>{i%2?'messages.read, events.read':'members.read, messages.read'}</span></div><button onClick={()=>notify(`${x} permissions opened`)}><Settings size={16}/></button><button onClick={()=>notify(`${x} revoked`)}><Trash2 size={16}/></button></div>)}</div><Button primary onClick={()=>go?.('app')}><Plus size={15}/> Install app</Button></>;
  return <GenericWorkflow title={titleFor(id)} notify={notify} go={go}/>;
}

function MoneyWorkflow({id, notify, go}: Props){
  if(id==='wallet' || id==='payouts' || id==='transactions') return <><div className="ev-balance-grid"><div><span>Available</span><b>$842.00</b></div><div><span>Pending</span><b>$126.40</b></div><div><span>This month</span><b>$2,184</b></div></div><div className="ev-table-wrap"><table className="ev-table"><thead><tr><th>Reference</th><th>Type</th><th>Status</th><th>Amount</th></tr></thead><tbody>{[['TX-1842','Creator earnings','Completed','+$84.20'],['TX-1841','Coin purchase','Completed','-$20.00'],['TX-1840','Payout','Pending','-$250.00'],['TX-1839','Refund','Completed','+$18.00']].map(r=><tr key={r[0]}><td><b>{r[0]}</b></td><td>{r[1]}</td><td>{r[2]}</td><td>{r[3]}</td></tr>)}</tbody></table></div><div className="ev-workflow-actions"><Button onClick={()=>notify('Deposit flow opened')}><Wallet size={15}/> Deposit</Button><Button onClick={()=>notify('Withdrawal verification opened')}><Download size={15}/> Withdraw</Button><Button onClick={()=>notify('Payout method opened')}><Settings size={15}/> Payout settings</Button></div></>;
  if(id==='coins') return <><div className="ev-coin-balance"><span>Everything Coins</span><b>8,420</b><small>Separate from real-money Wallet</small></div><div className="ev-coin-packs">{[['500','5.00'],['1,200','10.00'],['3,000','24.00'],['10,000','75.00']].map(([coins,price])=><button key={coins} onClick={()=>notify(`${coins} coin pack selected`)}><b>{coins}</b><span>coins</span><strong>${price}</strong></button>)}</div><div className="ev-check-list"><CheckRow>Use coins for eligible gifts, tips and paid interactions</CheckRow><CheckRow>Coin purchases are not physical marketplace payments</CheckRow></div></>;
  if(id==='subscription') return <><div className="ev-plan-grid">{[['Monthly','$9.99'],['6 Months','$49.99'],['1 Year','$79.99']].map(([x,p],i)=><button key={x} className={i===1?'featured':''} onClick={()=>notify(`${x} subscription selected`)}><span>{x}</span><b>{p}</b><small>Configurable Everything entitlements</small></button>)}</div><div className="ev-check-list"><CheckRow>Longer durations can unlock additional access</CheckRow><CheckRow>Subscription is centralized across Everything</CheckRow></div></>;
  if(id==='billing') return <><div className="ev-payment-list">{['Visa •••• 4242','Bank transfer','Supported provider'].map((x,i)=><div key={x}><CreditIcon/><div><b>{x}</b><span>{i===0?'Default payment method':'Available for supported flows'}</span></div></div>)}</div><Button primary onClick={()=>go?.('billing')}><Plus size={15}/> Add payment method</Button></>;
  return <GenericWorkflow title={titleFor(id)} notify={notify} go={go}/>;
}
function CreditIcon(){return <span className="ev-tile-icon">$</span>}

function IdentityWorkflow({id, notify, go}: Props){
  if(id==='profile' || id==='signup') return <><div className="ev-profile-editor"><div className="ev-profile-avatar">CK</div><Button onClick={()=>notify('Profile image picker opened')}><Upload size={15}/> Change photo</Button></div><div className="ev-form-grid"><Field label="Username"><input defaultValue="chessking"/></Field><Field label="Display name"><input defaultValue="Chess King"/></Field><Field label="Email"><input defaultValue="chessking@example.com"/></Field><Field label="Password"><input type="password" placeholder="••••••••"/></Field></div><Field label="Bio"><textarea defaultValue="Building Everything — social, communities, commerce and creator tools in one place."/></Field><Button primary onClick={()=>notify('Profile saved')}><Save size={15}/> Save profile</Button></>;
  if(id==='sessions') return <SessionWorkflow notify={notify}/>;
  if(id==='privacy' || id==='security' || id==='connected') return <><div className="ev-security-settings">{['Who can message me','Who can mention me','Show online status','Two-step verification','Passkeys','Connected app access'].map((x,i)=><label key={x}><span><b>{x}</b><small>{i<3?'Privacy control':'Security/access control'}</small></span><input type="checkbox" defaultChecked={i!==1}/></label>)}</div><Button primary onClick={()=>notify('Security/privacy settings saved')}><Save size={15}/> Save settings</Button></>;
  return <GenericWorkflow title={titleFor(id)} notify={notify} go={go}/>;
}

function DeveloperWorkflow({id, notify, go}: Props){
  if(id==='developer' || id==='app') return <><div className="ev-form-grid"><Field label="App name"><input placeholder="My Everything App"/></Field><Field label="Environment"><select><option>Sandbox</option><option>Production</option></select></Field><Field label="OAuth callback"><input placeholder="https://example.com/callback"/></Field><Field label="Permissions"><input placeholder="members.read, events.read"/></Field></div><div className="ev-sponsor-note"><Lock size={17}/><span>Secrets stay server-side. The frontend only displays masked credential metadata.</span></div><Button primary onClick={()=>serverAction('/developer/apps', 'POST', { status: 'draft' }).then(() => notify('Developer app saved on the server.')).catch((e) => notify(e.message || 'App save failed.'))}><Save size={15}/> Save app</Button></>;
  if(id==='webhooks') return <><div className="ev-form-grid"><Field label="Endpoint URL"><input placeholder="https://example.com/webhooks/everything"/></Field><Field label="Events"><input placeholder="member.joined, message.created"/></Field></div><div className="ev-webhook-list">{['member.joined · Delivered','message.created · Delivered','payment.completed · Retry scheduled'].map(x=><div key={x}><Webhook size={17}/><span>{x}</span><Check size={15}/></div>)}</div><Button primary onClick={()=>serverAction('/developer/webhooks', 'POST', { status: 'active' }).then(() => notify('Webhook saved on the server.')).catch((e) => notify(e.message || 'Webhook save failed.'))}><Plus size={15}/> Add webhook</Button></>;
  if(id==='api-keys') return <><div className="ev-key-list">{['Production app ·••••••7K2','Community bot ·••••••1P9','Sandbox test ·••••••4Q8'].map((x,i)=><div key={x}><KeyIcon/><div><b>{x}</b><span>{i===2?'Sandbox':'Scoped server-side credential'} · {i===1?'messages.read':'events.read'}</span></div><button onClick={()=>go?.('api-keys')}><Settings size={16}/></button></div>)}</div><Button primary onClick={()=>go?.('api-keys')}><Plus size={15}/> Create credential</Button></>;
  if(id==='events-api' || id==='logs') return <EventCatalogWorkflow />;
  return <GenericWorkflow title={titleFor(id)} notify={notify} go={go}/>;
}
function KeyIcon(){return <span className="ev-tile-icon"><KeyRound size={16}/></span>}

function SafetyWorkflow({id, notify, go}: Props){
  if(id==='appeal') return <><div className="ev-timeline"><div className="done"><span>1</span><div><b>Decision received</b><small>Reference SAF-2048</small></div></div><div><span>2</span><div><b>Context submitted</b><small>Pending review</small></div></div><div><span>3</span><div><b>Support response</b><small>Shown in Notifications when available</small></div></div></div><Field label="Additional context"><textarea placeholder="Explain the context for your appeal..."/></Field><Button primary onClick={()=>serverAction('/safety/appeals', 'POST').then(() => notify('Appeal submitted to the server.')).catch((e) => notify(e.message || 'Appeal submission failed.'))}><Send size={15}/> Submit appeal</Button></>;
  if(id==='content-controls') return <><div className="ev-security-settings">{['Sensitive content','Autoplay','Recommendations','Download permissions','External link previews'].map((x,i)=><label key={x}><span><b>{x}</b><small>Account-level content preference</small></span><input type="checkbox" defaultChecked={i !== 0}/></label>)}</div><Button primary onClick={()=>serverAction('/settings/content', 'PATCH', { saved: true }).then(() => notify('Content controls saved on the server.')).catch((e) => notify(e.message || 'Settings save failed.'))}><Save size={15}/> Save controls</Button></>;
  if(id==='report') return <><Field label="What are you reporting?"><select><option>Post</option><option>Comment</option><option>Message</option><option>User</option><option>Community</option></select></Field><Field label="Reason"><select><option>Spam</option><option>Scam / fraud</option><option>Harassment</option><option>Unsafe content</option><option>Other</option></select></Field><Field label="Additional context"><textarea placeholder="Optional details"/></Field><Button primary onClick={()=>serverAction('/safety/reports', 'POST').then(() => notify('Report submitted to the server.')).catch((e) => notify(e.message || 'Report submission failed.'))}><Flag size={15}/> Submit report</Button></>;
  if(id==='blocked') return <BlockedWorkflow go={go}/>;
  if(id==='privacy-download') return <><div className="ev-export-box"><Download size={28}/><div><b>Export your Everything data</b><span>Profile, posts, messages, saved items and available account data.</span></div><Button onClick={()=>serverAction('/data/export', 'POST').then(() => notify('Export request queued by the server.')).catch((e) => notify(e.message || 'Export request failed.'))}><Download size={15}/> Request export</Button></div><div className="ev-check-list"><CheckRow>Export request status is shown in Notifications</CheckRow><CheckRow>Download access is permission-checked</CheckRow></div></>;
  return <GenericWorkflow title={titleFor(id)} notify={notify} go={go}/>;
}

function SettingsWorkflow({id, notify, go}: Props){
  return <><div className="ev-settings-grid-wide">{['Notification categories','Theme & density','Language & region','Messaging controls','Content preferences','Help & support'].map((x,i)=><button key={x} onClick={()=>go?.(({ 'Notification categories':'notifications', 'Theme & density':'appearance', 'Language & region':'language', 'Messaging controls':'messages-settings', 'Content preferences':'content-controls', 'Help & support':'help' } as Record<string,string>)[x] || 'help')}><Settings size={18}/><div><b>{x}</b><span>{i===0?'Likes, replies, follows, messages, wallet and security':i===1?'Appearance, motion and accessibility':i===2?'Language, time zone and currency':'Manage this Everything preference group'}</span></div><ChevronRight size={15}/></button>)}</div><Button primary onClick={()=>serverAction('/settings', 'PATCH', { saved: true }).then(() => notify('Settings saved on the server.')).catch((e) => notify(e.message || 'Settings save failed.'))}><Save size={15}/> Save changes</Button></>;
}

function GenericWorkflow({title, go}: {title:string; notify:(m:string)=>void; go?: (id:string)=>void}){ const [q,setQ]=useState(''); const map:Record<string,string>={Overview:'community','Recent activity':'notifications',Permissions:'members',Notifications:'notifications',Analytics:'community-analytics',Safety:'report'}; const target=title.toLowerCase().includes('developer')?'developer':title.toLowerCase().includes('community')?'community':undefined; return <><div className="ev-generic-toolbar"><div className="ev-inline-search"><Search size={16}/><input value={q} onChange={e=>setQ(e.target.value)} placeholder={`Search ${title.toLowerCase()}...`}/></div>{go&&target&&<Button onClick={()=>go(target)}><Plus size={15}/> Create</Button>}</div><div className="ev-generic-grid">{['Overview','Recent activity','Permissions','Notifications','Analytics','Safety'].filter(x=>x.toLowerCase().includes(q.toLowerCase())||!q).map(x=><button type="button" key={x} className="ev-generic-grid-item" onClick={()=>go?.(map[x] || target || 'help')}><span className="ev-tile-icon"><Check size={16}/></span><div><b>{x}</b><small>Open this workspace section</small></div><ChevronRight size={15}/></button>)}</div></>; }

function SessionWorkflow({notify}:{notify:(m:string)=>void}){ const [sessions,setSessions]=useState<string[]>([]); const load=()=>apiClient.request<any[]>('/auth/sessions').then(r=>setSessions((r.data||[]).map((x:any)=>String(x.id||x.device||x.userAgent||'Session')))).catch((e)=>notify(e.message||'Unable to load sessions.')); React.useEffect(load,[]); const revoke=(id:string)=>apiClient.request(`/auth/sessions/${encodeURIComponent(id)}`,{method:'DELETE'}).then(()=>setSessions(v=>v.filter(x=>x!==id))).catch((e)=>notify(e.message||'Unable to revoke session.')); return <><div className="ev-session-list">{sessions.length===0?<p>No other active sessions returned by the server.</p>:sessions.map(x=><div key={x}><Smartphone size={18}/><div><b>{x}</b><span>Server-reported session</span></div><button type="button" onClick={()=>revoke(x)}><X size={16}/></button></div>)}</div>{sessions.length>0&&<Button primary onClick={()=>apiClient.request('/auth/logout-all',{method:'POST'}).then(()=>{setSessions([]);notify('Other sessions revoked by the server.')}).catch((e)=>notify(e.message||'Unable to revoke sessions.'))}><ShieldCheck size={15}/> Sign out other sessions</Button>}</>; }
function BlockedWorkflow({go}:{go?: (id:string)=>void}){ const [items,setItems]=useState<string[]>([]); React.useEffect(()=>{apiClient.request<any[]>('/safety/blocked').then(r=>setItems((r.data||[]).map((x:any)=>String(x.id||x.username||x.name||'')))).catch(()=>setItems([]));},[]); const unblock=(id:string)=>apiClient.request(`/safety/blocked/${encodeURIComponent(id)}`,{method:'DELETE'}).then(()=>setItems(v=>v.filter(x=>x!==id))); return <><div className="ev-block-list">{items.length===0?<p>No blocked users returned by the server.</p>:items.map(x=><div key={x}><ShieldCheck size={17}/><b>{x}</b><button type="button" onClick={()=>unblock(x)}>Unblock</button></div>)}</div>{go&&<Button primary onClick={()=>go('report')}><UserPlus size={15}/> Block user</Button>}</>; }
function EventCatalogWorkflow(){ const [selected,setSelected]=useState<string|null>(null); const events=['member.joined','member.left','message.created','message.deleted','post.created','reaction.added','event.started','payment.completed']; return <><div className="ev-event-list">{events.map(x=><button key={x} type="button" onClick={()=>setSelected(x)}><code>{x}</code><ChevronRight size={15}/></button>)}</div>{selected&&<div className="ev-form-note"><b>{selected}</b><span>Event schema details and delivery permissions are available here; provider/API configuration remains server-side.</span><button type="button" onClick={()=>setSelected(null)} aria-label="Close event details"><X size={15}/></button></div>}</>}

function titleFor(id:string){return id.replaceAll('-',' ').replace(/\b\w/g,c=>c.toUpperCase());}

export default function EverythingWorkflowScreens(props: Props){
  const {id}=props;
  if(['post','html','reel','video','channel','live','live-studio','media'].includes(id)) return <ContentWorkflow {...props}/>;
  if(['product','seller','seller-product','buyer-chat','order','event','ads'].includes(id)) return <CommerceWorkflow {...props}/>;
  if(['community','members','channels','moderation','automation','bots','community-store','community-analytics'].includes(id)) return <CommunityWorkflow {...props}/>;
  if(['wallet','coins','payouts','transactions','subscription','billing'].includes(id)) return <MoneyWorkflow {...props}/>;
  if(['profile','signup','sessions','privacy','security','connected'].includes(id)) return <IdentityWorkflow {...props}/>;
  if(['developer','app','webhooks','api-keys','events-api','logs'].includes(id)) return <DeveloperWorkflow {...props}/>;
  if(['report','blocked','appeal','privacy-download','content-controls'].includes(id)) return <SafetyWorkflow {...props}/>;
  if(['notifications','appearance','language','messages-settings','help'].includes(id)) return <SettingsWorkflow {...props}/>;
  return <GenericWorkflow title={props.title} notify={props.notify} go={props.go}/>;
}
